services:
  # PHP-FPM сервис
  php-fpm:
    image: php:8.1-fpm # Можно указать другую версию PHP
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html # Папка с вашим кодом
    networks:
      - app-network

  # Nginx сервис
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./www:/var/www/html # Папка с вашим кодом
      - ./nginx.conf:/etc/nginx/nginx.conf # Конфигурация Nginx
      # - ./sites:/etc/nginx/sites-available # Конфигурация сайтов (опционально)
    ports:
      - "80:80" # Публикуем порт 80 для доступа из браузера
    depends_on:
      - php-fpm # Nginx зависит от PHP-FPM
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
